---
name: test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn run lint
    - run: docker run -d --rm --name=dev-consul --network host consul
    - run: yarn test
    - if: ${{ always() }}
      run: docker stop dev-consul

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker run -d --rm --name=dev-consul --network host consul
    - uses: ./
      with:
        key: foo
        value: bar
    - uses: ./
      id: test
      with:
        key: boo
    - name: Fail action
      if: ${{ steps.test.outputs.data != 'bar' }}
      run: exit 1
    - if: ${{ always() }}
      run: docker stop dev-consul
